In [9]:
import numpy as np
import pandas as pd
import matplotlib as mlt
import seaborn as sb
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os
from concurrent.futures import ThreadPoolExecutor



load_dotenv()

True

In [10]:
DATABASE_URL = os.getenv("DATABASE_URL")
sql_engine = create_engine(DATABASE_URL)

In [11]:
# data = pd.read_csv("activity.csv") # old implementation ; but now i am directly pooling data from database
# data pooling staement section started here
select_activity_stm = "SELECT * FROM activity"
select_body_battery_activity_events_stm = "SELECT * FROM body_battery_activity_events"
select_body_battery_sample_stm = "SELECT * FROM body_battery_sample"
select_goals_stm = "SELECT * FROM goals"
select_heart_rate_sample_stm = "SELECT * FROM heart_rate_sample"
select_heart_rate_values_stm = "SELECT * FROM heart_rate_values"
select_kilocalories_stm = "SELECT * FROM kilocalories"
select_overall_sleep_stm = "SELECT * FROM overall_sleep"
select_sleep_stm = "SELECT * FROM sleep"
select_sleep_level_events_stm = "SELECT * FROM sleep_level_events"
select_steps_stm = "SELECT * FROM steps"
select_stress_stm = "SELECT * FROM stress"
select_stress_level_sample_stm = "SELECT * FROM stress_level_sample"
# data pooling statement section ends here

# These are synchronous operations therefore taking too long to execute; Because database is huge; i need a concurrent solution
# activity_data = pd.read_sql(select_activity_stm, sql_engine)
# body_battery_activity_events_data = pd.read_sql(select_body_battery_activity_events_stm, sql_engine)
# body_battery_sample_data = pd.read_sql(select_body_battery_sample_stm, sql_engine)
# goals_data = pd.read_sql(select_goals_stm, sql_engine)
# heart_rate_sample_data = pd.read_sql(select_heart_rate_sample_stm, sql_engine)
# heart_rate_values_data = pd.read_sql(select_heart_rate_values_stm, sql_engine)
# kilocalories_data = pd.read_sql(select_kilocalories_stm, sql_engine)
# overall_sleep_data = pd.read_sql(select_overall_sleep_stm, sql_engine)
# sleep_data = pd.read_sql(select_sleep_stm, sql_engine)
# sleep_level_events_data = pd.read_sql(select_sleep_level_events_stm, sql_engine)
# steps_data = pd.read_sql(select_steps_stm, sql_engine)
# stress_data = pd.read_sql(select_stress_stm, sql_engine)
# stress_level_sample_data = pd.read_sql(select_stress_level_sample_stm, sql_engine)
# activity_data = pd.read_sql(select_activity_stm,sql_engine)
# goals_data = pd.read_sql(select_goals_stm, sql_engine)
# synchronous datapooling section ends here

# trying threadpools for data pooling

queries = {
    "activity_data": select_activity_stm,
    "body_battery_activity_events_data": select_body_battery_activity_events_stm,
    "body_battery_sample_data": select_body_battery_sample_stm,
    "goals_data": select_goals_stm,
    "heart_rate_sample_data": select_heart_rate_sample_stm,
    "heart_rate_values_data": select_heart_rate_values_stm,
    "kilocalories_data": select_kilocalories_stm,
    "overall_sleep_data": select_overall_sleep_stm,
    "sleep_data": select_sleep_stm,
    "sleep_level_events_data": select_sleep_level_events_stm,
    "steps_data": select_steps_stm,
    "stress_data": select_stress_stm,
    "stress_level_sample_data": select_stress_level_sample_stm,
}

def load_table(item):
    name, query = item

    with sql_engine.connect() as connection:
        df = pd.read_sql(query, connection)

    print(f"Loaded {name}: {len(df):,} rows")
    return name, df

with ThreadPoolExecutor(max_workers=4) as executor:
    results = executor.map(load_table, queries.items())

dataframes = dict(results)

# Access your DataFrames using the original variable names
activity_data = dataframes["activity_data"]
body_battery_activity_events_data = dataframes["body_battery_activity_events_data"]
body_battery_sample_data = dataframes["body_battery_sample_data"]
goals_data = dataframes["goals_data"]
heart_rate_sample_data = dataframes["heart_rate_sample_data"]
heart_rate_values_data = dataframes["heart_rate_values_data"]
kilocalories_data = dataframes["kilocalories_data"]
overall_sleep_data = dataframes["overall_sleep_data"]
sleep_data = dataframes["sleep_data"]
sleep_level_events_data = dataframes["sleep_level_events_data"]
steps_data = dataframes["steps_data"]
stress_data = dataframes["stress_data"]
stress_level_sample_data = dataframes["stress_level_sample_data"]

Loaded body_battery_activity_events_data: 448 rows
Loaded activity_data: 987 rows
Loaded goals_data: 987 rows
Loaded heart_rate_values_data: 961 rows
Loaded kilocalories_data: 987 rows
Loaded overall_sleep_data: 299 rows
Loaded sleep_data: 299 rows
Loaded steps_data: 987 rows
Loaded stress_data: 987 rows
Loaded sleep_level_events_data: 18,402 rows
Loaded body_battery_sample_data: 315,848 rows
Loaded stress_level_sample_data: 460,975 rows
Loaded heart_rate_sample_data: 4,912,004 rows

In [13]:
# Testing whether the concurrent  pooling worked and we have all the table with data available.
print("activity_data:", activity_data.shape)
print("body_battery_activity_events_data:", body_battery_activity_events_data.shape)
print("body_battery_sample_data:", body_battery_sample_data.shape)
print("goals_data:", goals_data.shape)
print("heart_rate_sample_data:", heart_rate_sample_data.shape)
print("heart_rate_values_data:", heart_rate_values_data.shape)
print("kilocalories_data:", kilocalories_data.shape)
print("overall_sleep_data:", overall_sleep_data.shape)
print("sleep_data:", sleep_data.shape)
print("sleep_level_events_data:", sleep_level_events_data.shape)
print("steps_data:", steps_data.shape)
print("stress_data:", stress_data.shape)
print("stress_level_sample_data:", stress_level_sample_data.shape)

activity_data: (987, 16)
body_battery_activity_events_data: (448, 14)
body_battery_sample_data: (315848, 12)
goals_data: (987, 13)
heart_rate_sample_data: (4912004, 12)
heart_rate_values_data: (961, 14)
kilocalories_data: (987, 12)
overall_sleep_data: (299, 12)
sleep_data: (299, 17)
sleep_level_events_data: (18402, 13)
steps_data: (987, 12)
stress_data: (987, 19)
stress_level_sample_data: (460975, 12)

In [14]:
# creating a database inventory to understand the database 

dataframes = {
    "activity_data": activity_data,
    "body_battery_activity_events_data": body_battery_activity_events_data,
    "body_battery_sample_data": body_battery_sample_data,
    "goals_data": goals_data,
    "heart_rate_sample_data": heart_rate_sample_data,
    "heart_rate_values_data": heart_rate_values_data,
    "kilocalories_data": kilocalories_data,
    "overall_sleep_data": overall_sleep_data,
    "sleep_data": sleep_data,
    "sleep_level_events_data": sleep_level_events_data,
    "steps_data": steps_data,
    "stress_data": stress_data,
    "stress_level_sample_data": stress_level_sample_data,
}

# 2. Create a database inventory
inventory = []

for name, df in dataframes.items():
    inventory.append({
        "table": name,
        "rows": len(df),
        "columns": len(df.columns),
        "memory_MB": round(
            df.memory_usage(deep=True).sum() / 1024**2, 2
        ),
    })

inventory_df = pd.DataFrame(inventory)

print("DATABASE INVENTORY")
display(inventory_df)

# 3. Inspect column names, data types and example values
for name, df in dataframes.items():
    print(f"\n{'=' * 80}")
    print(f"TABLE: {name}")
    print(f"Shape: {df.shape}")

    schema = pd.DataFrame({
        "column": df.columns,
        "dtype": [str(dtype) for dtype in df.dtypes],
        "missing_count": df.isna().sum().values,
        "missing_percent": (
            df.isna().mean().mul(100).round(2).values
        ),
        "unique_values": df.nunique(dropna=True).values,
    })

    display(schema)
    print("First 3 rows:")
    display(df.head(3))

# 4. Create a data-quality summary
quality = []

for name, df in dataframes.items():
    total_cells = df.size
    missing_cells = int(df.isna().sum().sum())

    quality.append({
        "table": name,
        "rows": len(df),
        "missing_cells": missing_cells,
        "missing_percent": round(
            missing_cells / total_cells * 100, 2
        ) if total_cells else 0,
        "duplicate_rows": int(df.duplicated().sum()),
    })

quality_df = pd.DataFrame(quality)

print("\nDATA QUALITY SUMMARY")
display(quality_df)

# 5. Summarise numerical columns
for name, df in dataframes.items():
    numeric = df.select_dtypes(include="number")

    if not numeric.empty:
        print(f"\nNUMERICAL SUMMARY: {name}")
        display(numeric.describe().T)

DATABASE INVENTORY

                                table     rows  columns  memory_MB
0                       activity_data      987       16       0.28
1   body_battery_activity_events_data      448       14       0.14
2            body_battery_sample_data   315848       12      78.57
3                          goals_data      987       13       0.25
4              heart_rate_sample_data  4912004       12    1222.59
5              heart_rate_values_data      961       14       0.25
6                   kilocalories_data      987       12       0.25
7                  overall_sleep_data      299       12       0.09
8                          sleep_data      299       17       0.19
9             sleep_level_events_data    18402       13       5.65
10                         steps_data      987       12       0.25
11                        stress_data      987       19       0.35
12           stress_level_sample_data   460975       12     114.77

================================================================================
TABLE: activity_data
Shape: (987, 16)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.00,987
1,sdv_user_id,int64,0,0.00,8
2,sdv_group_id,int64,0,0.00,3
3,sdv_data_type,str,0,0.00,1
4,calendar_date,object,0,0.00,251
5,start_measure_period_sec,int64,0,0.00,259
6,end_measure_period_sec,int64,0,0.00,272
7,duration_measure_period_sec,int64,0,0.00,17
8,week_nr,int64,0,0.00,37
9,week_day,int64,0,0.00,7
10,distance_in_meters,int64,0,0.00,926
11,steps,int64,0,0.00,931
12,floors_climbed,float64,558,56.53,50
13,active_time_sec,int64,0,0.00,905
14,moderate_intensity_duration_sec,int64,0,0.00,119
15,vigorous_intensity_duration_sec,int64,0,0.00,92

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,distance_in_meters,steps,floors_climbed,active_time_sec,moderate_intensity_duration_sec,vigorous_intensity_duration_sec
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,11826,16204,NaN,13439,1140,0
1,x6607386-6a18bae0-15180-0,4408,7552,garmin_type,2026-05-29,1780005600,1780092000,86400,22,5,60,82,NaN,300,0,0
2,x6607386-6a176960-15180-0,4408,7552,garmin_type,2026-05-28,1779919200,1780005600,86400,22,4,2180,2987,NaN,3966,420,60

================================================================================
TABLE: body_battery_activity_events_data
Shape: (448, 14)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,178
1,sdv_user_id,int64,0,0.0,2
2,sdv_group_id,int64,0,0.0,1
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,136
5,start_measure_period_sec,int64,0,0.0,136
6,end_measure_period_sec,int64,0,0.0,136
7,duration_measure_period_sec,int64,0,0.0,2
8,week_nr,int64,0,0.0,20
9,week_day,int64,0,0.0,7
10,eventtype,str,0,0.0,5
11,start_sec,int64,0,0.0,448
12,duration_sec,int64,0,0.0,224
13,bodybatteryimpact,float64,0,0.0,87

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,eventtype,start_sec,duration_sec,bodybatteryimpact
0,x56c4701-6a77a6e0-15180-0,3760,7553,garmin_type,2026-08-09,1786226400,1786312800,86400,32,7,SLEEP,1786229682,25800,56.0
1,x56c4701-6a77a6e0-15180-0,3760,7553,garmin_type,2026-08-09,1786226400,1786312800,86400,32,7,ACTIVITY,1786259043,4260,-11.0
2,x56c4701-6a765560-15180-0,3760,7553,garmin_type,2026-08-08,1786140000,1786226400,86400,32,6,SLEEP,1786141928,28800,69.0

================================================================================
TABLE: body_battery_sample_data
Shape: (315848, 12)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,708
1,sdv_user_id,int64,0,0.0,7
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,242
5,start_measure_period_sec,int64,0,0.0,250
6,end_measure_period_sec,int64,0,0.0,259
7,duration_measure_period_sec,int64,0,0.0,13
8,week_nr,int64,0,0.0,37
9,week_day,int64,0,0.0,7
10,sample_point_sec,int64,0,0.0,115444
11,body_battery_value,int64,0,0.0,96

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,sample_point_sec,body_battery_value
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,1780092000,25
1,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,1780092180,25
2,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,1780092360,25

================================================================================
TABLE: goals_data
Shape: (987, 13)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,987
1,sdv_user_id,int64,0,0.0,8
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,251
5,start_measure_period_sec,int64,0,0.0,259
6,end_measure_period_sec,int64,0,0.0,272
7,duration_measure_period_sec,int64,0,0.0,17
8,week_nr,int64,0,0.0,37
9,week_day,int64,0,0.0,7
10,steps_goal,int64,0,0.0,297
11,floors_goal,int64,0,0.0,2
12,intensity_goal,int64,0,0.0,3

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,steps_goal,floors_goal,intensity_goal
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,10000,10,9000
1,x6607386-6a18bae0-15180-0,4408,7552,garmin_type,2026-05-29,1780005600,1780092000,86400,22,5,10000,10,9000
2,x6607386-6a176960-15180-0,4408,7552,garmin_type,2026-05-28,1779919200,1780005600,86400,22,4,10000,10,9000

================================================================================
TABLE: heart_rate_sample_data
Shape: (4912004, 12)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,960
1,sdv_user_id,int64,0,0.0,8
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,251
5,start_measure_period_sec,int64,0,0.0,259
6,end_measure_period_sec,int64,0,0.0,267
7,duration_measure_period_sec,int64,0,0.0,12
8,week_nr,int64,0,0.0,37
9,week_day,int64,0,0.0,7
10,sample_point_sec,int64,0,0.0,1440880
11,heart_rate,int64,0,0.0,169

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,sample_point_sec,heart_rate
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,1780092015,79
1,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,1780092030,79
2,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,1780092045,79

================================================================================
TABLE: heart_rate_values_data
Shape: (961, 14)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,961
1,sdv_user_id,int64,0,0.0,8
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,251
5,start_measure_period_sec,int64,0,0.0,259
6,end_measure_period_sec,int64,0,0.0,267
7,duration_measure_period_sec,int64,0,0.0,12
8,week_nr,int64,0,0.0,37
9,week_day,int64,0,0.0,7
10,min_heart_rate_min,float64,1,0.1,49
11,max_heart_rate_min,float64,1,0.1,104
12,avg_heart_rate_min,float64,1,0.1,45
13,rest_heart_rate_min,int64,0,0.0,37

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,min_heart_rate_min,max_heart_rate_min,avg_heart_rate_min,rest_heart_rate_min
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,67.0,137.0,92.0,69
1,x6607386-6a18bae0-15180-0,4408,7552,garmin_type,2026-05-29,1780005600,1780092000,86400,22,5,70.0,102.0,82.0,77
2,x6607386-6a176960-15180-0,4408,7552,garmin_type,2026-05-28,1779919200,1780005600,86400,22,4,65.0,141.0,85.0,70

================================================================================
TABLE: kilocalories_data
Shape: (987, 12)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,987
1,sdv_user_id,int64,0,0.0,8
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,251
5,start_measure_period_sec,int64,0,0.0,259
6,end_measure_period_sec,int64,0,0.0,272
7,duration_measure_period_sec,int64,0,0.0,17
8,week_nr,int64,0,0.0,37
9,week_day,int64,0,0.0,7
10,active_kilocalories,int64,0,0.0,590
11,bmr_kilocalories,int64,0,0.0,60

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,active_kilocalories,bmr_kilocalories
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,1001,2191
1,x6607386-6a18bae0-15180-0,4408,7552,garmin_type,2026-05-29,1780005600,1780092000,86400,22,5,4,2414
2,x6607386-6a176960-15180-0,4408,7552,garmin_type,2026-05-28,1779919200,1780005600,86400,22,4,309,2414

================================================================================
TABLE: overall_sleep_data
Shape: (299, 12)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,299
1,sdv_user_id,int64,0,0.0,5
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,133
5,start_measure_period_sec,int64,0,0.0,139
6,end_measure_period_sec,int64,0,0.0,143
7,duration_measure_period_sec,int64,0,0.0,7
8,week_nr,int64,0,0.0,20
9,week_day,int64,0,0.0,7
10,sleep_value,int64,0,0.0,64
11,sleep_qualifier,str,0,0.0,4

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,sleep_value,sleep_qualifier
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,66,FAIR
1,x6607386-6a176960-15180-0,4408,7552,garmin_type,2026-05-28,1779919200,1780005600,86400,22,4,49,POOR
2,x6607386-6a1617e0-15180-0,4408,7552,garmin_type,2026-05-27,1779832800,1779919200,86400,22,3,47,POOR

================================================================================
TABLE: sleep_data
Shape: (299, 17)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,299
1,sdv_user_id,int64,0,0.0,5
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,133
5,start_measure_period_sec,int64,0,0.0,139
6,end_measure_period_sec,int64,0,0.0,143
7,duration_measure_period_sec,int64,0,0.0,7
8,week_nr,int64,0,0.0,20
9,week_day,int64,0,0.0,7
10,total_duration,str,0,0.0,4
11,stress,str,0,0.0,4
12,awake,str,0,0.0,4
13,remperc,str,0,0.0,5
14,restless,str,0,0.0,4
15,lightperc,str,0,0.0,5
16,deepperc,str,0,0.0,5

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,total_duration,stress,awake,remperc,restless,lightperc,deepperc
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,EXCELLENT,POOR,EXCELLENT,FAIR,EXCELLENT,GOOD,EXCELLENT
1,x6607386-6a176960-15180-0,4408,7552,garmin_type,2026-05-28,1779919200,1780005600,86400,22,4,GOOD,POOR,EXCELLENT,FAIR,EXCELLENT,FAIR,EXCELLENT
2,x6607386-6a1617e0-15180-0,4408,7552,garmin_type,2026-05-27,1779832800,1779919200,86400,22,3,FAIR,POOR,EXCELLENT,FAIR,EXCELLENT,FAIR,EXCELLENT

================================================================================
TABLE: sleep_level_events_data
Shape: (18402, 13)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,797
1,sdv_user_id,int64,0,0.0,8
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,249
5,start_measure_period_sec,int64,0,0.0,255
6,end_measure_period_sec,int64,0,0.0,262
7,duration_measure_period_sec,int64,0,0.0,10
8,week_nr,int64,0,0.0,37
9,week_day,int64,0,0.0,7
10,sleeptype,str,0,0.0,4
11,start_sec,int64,0,0.0,17785
12,end_sec,int64,0,0.0,17789

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,sleeptype,start_sec,end_sec
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,deep,1780092600,1780095900
1,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,deep,1780099260,1780099800
2,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,deep,1780100580,1780103400

================================================================================
TABLE: steps_data
Shape: (987, 12)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,987
1,sdv_user_id,int64,0,0.0,8
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,251
5,start_measure_period_sec,int64,0,0.0,259
6,end_measure_period_sec,int64,0,0.0,272
7,duration_measure_period_sec,int64,0,0.0,17
8,week_nr,int64,0,0.0,37
9,week_day,int64,0,0.0,7
10,steps,int64,0,0.0,931
11,steps_goal,int64,0,0.0,297

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,steps,steps_goal
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,16204,10000
1,x6607386-6a18bae0-15180-0,4408,7552,garmin_type,2026-05-29,1780005600,1780092000,86400,22,5,82,10000
2,x6607386-6a176960-15180-0,4408,7552,garmin_type,2026-05-28,1779919200,1780005600,86400,22,4,2987,10000

================================================================================
TABLE: stress_data
Shape: (987, 19)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.00,987
1,sdv_user_id,int64,0,0.00,8
2,sdv_group_id,int64,0,0.00,3
3,sdv_data_type,str,0,0.00,1
4,calendar_date,object,0,0.00,251
5,start_measure_period_sec,int64,0,0.00,259
6,end_measure_period_sec,int64,0,0.00,272
7,duration_measure_period_sec,int64,0,0.00,17
8,week_nr,int64,0,0.00,37
9,week_day,int64,0,0.00,7
10,average_stress_level,int64,0,0.00,66
11,max_stress_level,float64,27,2.74,35
12,stress_duration_sec,float64,27,2.74,541
13,rest_stress_duration_sec,float64,39,3.95,563
14,low_stress_duration_sec,float64,29,2.94,452
15,medium_stress_duration_sec,float64,31,3.14,324
16,high_stress_duration_sec,float64,42,4.26,221
17,activity_stress_duration_sec,float64,22,2.23,390
18,stress_qualifier,str,0,0.00,9

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,average_stress_level,max_stress_level,stress_duration_sec,rest_stress_duration_sec,low_stress_duration_sec,medium_stress_duration_sec,high_stress_duration_sec,activity_stress_duration_sec,stress_qualifier
0,x6607386-6a1a0c60-13254,4408,7552,garmin_type,2026-05-30,1780092000,1780170420,78420,22,6,59,99.0,41580.0,7620.0,11820.0,10260.0,19500.0,12900.0,very_stressful
1,x6607386-6a18bae0-15180-0,4408,7552,garmin_type,2026-05-29,1780005600,1780092000,86400,22,5,53,73.0,1620.0,NaN,720.0,900.0,NaN,15540.0,unknown
2,x6607386-6a176960-15180-0,4408,7552,garmin_type,2026-05-28,1779919200,1780005600,86400,22,4,56,99.0,38820.0,8160.0,5400.0,28740.0,4680.0,6120.0,unknown

================================================================================
TABLE: stress_level_sample_data
Shape: (460975, 12)

,column,dtype,missing_count,missing_percent,unique_values
0,additional_id,str,0,0.0,981
1,sdv_user_id,int64,0,0.0,8
2,sdv_group_id,int64,0,0.0,3
3,sdv_data_type,str,0,0.0,1
4,calendar_date,object,0,0.0,251
5,start_measure_period_sec,int64,0,0.0,259
6,end_measure_period_sec,int64,0,0.0,274
7,duration_measure_period_sec,int64,0,0.0,19
8,week_nr,int64,0,0.0,37
9,week_day,int64,0,0.0,7
10,sample_point_sec,int64,0,0.0,120459
11,stress_level,int64,0,0.0,102

First 3 rows:

,additional_id,sdv_user_id,sdv_group_id,sdv_data_type,calendar_date,start_measure_period_sec,end_measure_period_sec,duration_measure_period_sec,week_nr,week_day,sample_point_sec,stress_level
0,x5f21468-6a4ac954-6090,4274,7554,garmin_type,2026-07-06,1783288800,1783375200,86400,28,1,1783333440,65
1,x5f21468-6a4ac954-6090,4274,7554,garmin_type,2026-07-06,1783288800,1783375200,86400,28,1,1783333620,94
2,x5f21468-6a4ac954-6090,4274,7554,garmin_type,2026-07-06,1783288800,1783375200,86400,28,1,1783333800,-1

DATA QUALITY SUMMARY

,table,rows,missing_cells,missing_percent,duplicate_rows
0,activity_data,987,558,3.53,0
1,body_battery_activity_events_data,448,0,0.00,0
2,body_battery_sample_data,315848,0,0.00,0
3,goals_data,987,0,0.00,0
4,heart_rate_sample_data,4912004,0,0.00,0
5,heart_rate_values_data,961,3,0.02,0
6,kilocalories_data,987,0,0.00,0
7,overall_sleep_data,299,0,0.00,0
8,sleep_data,299,0,0.00,0
9,sleep_level_events_data,18402,0,0.00,0
10,steps_data,987,0,0.00,0
11,stress_data,987,217,1.16,0
12,stress_level_sample_data,460975,0,0.00,108

NUMERICAL SUMMARY: activity_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,987.0,4.200755e+03,2.156566e+02,3.724000e+03,4.274000e+03,4.286000e+03,4.306000e+03,4.408000e+03
sdv_group_id,987.0,7.553390e+03,5.202031e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,987.0,1.779292e+09,5.253043e+06,1.767222e+09,1.776118e+09,1.779401e+09,1.783462e+09,1.788818e+09
end_measure_period_sec,987.0,1.779378e+09,5.252706e+06,1.767308e+09,1.776204e+09,1.779487e+09,1.783548e+09,1.788905e+09
duration_measure_period_sec,987.0,8.577684e+04,6.286301e+03,3.000000e+02,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,987.0,2.095846e+01,8.694225e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,987.0,4.020263e+00,1.990748e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
distance_in_meters,987.0,6.651415e+03,6.348731e+03,0.000000e+00,2.590000e+03,4.386000e+03,8.457000e+03,4.478300e+04
steps,987.0,6.802246e+03,5.643962e+03,0.000000e+00,3.151000e+03,5.302000e+03,8.851500e+03,4.702500e+04
floors_climbed,429.0,9.853147e+00,1.326560e+01,0.000000e+00,2.000000e+00,6.000000e+00,1.300000e+01,1.180000e+02
active_time_sec,987.0,6.482641e+03,4.286535e+03,0.000000e+00,3.826000e+03,5.770000e+03,8.213000e+03,3.324500e+04
moderate_intensity_duration_sec,987.0,1.107356e+03,2.133746e+03,0.000000e+00,0.000000e+00,1.800000e+02,1.380000e+03,1.884000e+04
vigorous_intensity_duration_sec,987.0,6.715502e+02,1.494193e+03,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e+02,1.674000e+04

NUMERICAL SUMMARY: body_battery_activity_events_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,448.0,3.748911e+03,1.663911e+01,3.724000e+03,3.724000e+03,3.760000e+03,3.760000e+03,3.760000e+03
sdv_group_id,448.0,7.553000e+03,0.000000e+00,7.553000e+03,7.553000e+03,7.553000e+03,7.553000e+03,7.553000e+03
start_measure_period_sec,448.0,1.779762e+09,3.248335e+06,1.774566e+09,1.776982e+09,1.779228e+09,1.782360e+09,1.786226e+09
end_measure_period_sec,448.0,1.779848e+09,3.248314e+06,1.774652e+09,1.777068e+09,1.779314e+09,1.782446e+09,1.786313e+09
duration_measure_period_sec,448.0,8.622723e+04,2.582859e+03,4.770000e+04,8.640000e+04,8.640000e+04,8.640000e+04,8.640000e+04
week_nr,448.0,2.173438e+01,5.376099e+00,1.300000e+01,1.700000e+01,2.100000e+01,2.600000e+01,3.200000e+01
week_day,448.0,4.029018e+00,2.003701e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
start_sec,448.0,1.779791e+09,3.250189e+06,1.774560e+09,1.777042e+09,1.779246e+09,1.782399e+09,1.786259e+09
duration_sec,448.0,1.272121e+04,1.228122e+04,3.000000e+02,2.340000e+03,4.710000e+03,2.646000e+04,3.546000e+04
bodybatteryimpact,448.0,1.661384e+01,2.631823e+01,-2.200000e+01,-3.000000e+00,2.000000e+00,4.100000e+01,7.900000e+01

NUMERICAL SUMMARY: body_battery_sample_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,315848.0,4.150897e+03,2.454956e+02,3.724000e+03,3.760000e+03,4.274000e+03,4.286000e+03,4.408000e+03
sdv_group_id,315848.0,7.553518e+03,5.318811e-01,7.552000e+03,7.553000e+03,7.554000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,315848.0,1.779567e+09,4.758617e+06,1.767222e+09,1.776550e+09,1.779401e+09,1.783375e+09,1.788818e+09
end_measure_period_sec,315848.0,1.779653e+09,4.758577e+06,1.767308e+09,1.776636e+09,1.779487e+09,1.783462e+09,1.788905e+09
duration_measure_period_sec,315848.0,8.624018e+04,2.501991e+03,6.720000e+03,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,315848.0,2.141166e+01,7.879616e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,315848.0,4.025762e+00,1.990502e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
sample_point_sec,315848.0,1.779610e+09,4.758819e+06,1.767222e+09,1.776598e+09,1.779427e+09,1.783431e+09,1.788905e+09
body_battery_value,315848.0,4.121849e+01,2.199581e+01,5.000000e+00,2.500000e+01,3.900000e+01,5.600000e+01,1.000000e+02

NUMERICAL SUMMARY: goals_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,987.0,4.200755e+03,2.156566e+02,3.724000e+03,4.274000e+03,4.286000e+03,4.306000e+03,4.408000e+03
sdv_group_id,987.0,7.553390e+03,5.202031e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,987.0,1.779292e+09,5.253043e+06,1.767222e+09,1.776118e+09,1.779401e+09,1.783462e+09,1.788818e+09
end_measure_period_sec,987.0,1.779378e+09,5.252706e+06,1.767308e+09,1.776204e+09,1.779487e+09,1.783548e+09,1.788905e+09
duration_measure_period_sec,987.0,8.577684e+04,6.286301e+03,3.000000e+02,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,987.0,2.095846e+01,8.694225e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,987.0,4.020263e+00,1.990748e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
steps_goal,987.0,8.027082e+03,3.617580e+03,2.780000e+03,5.985000e+03,8.000000e+03,1.000000e+04,3.000000e+04
floors_goal,987.0,1.123607e+01,3.292994e+00,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,2.000000e+01
intensity_goal,987.0,9.899696e+03,2.251227e+03,9.000000e+03,9.000000e+03,9.000000e+03,9.000000e+03,1.800000e+04

NUMERICAL SUMMARY: heart_rate_sample_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,4912004.0,4.187830e+03,2.238591e+02,3.724000e+03,4.274000e+03,4.274000e+03,4.306000e+03,4.408000e+03
sdv_group_id,4912004.0,7.553404e+03,5.155973e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,4912004.0,1.779087e+09,5.239776e+06,1.767222e+09,1.776031e+09,1.779142e+09,1.783289e+09,1.788818e+09
end_measure_period_sec,4912004.0,1.779173e+09,5.239728e+06,1.767308e+09,1.776118e+09,1.779228e+09,1.783375e+09,1.788905e+09
duration_measure_period_sec,4912004.0,8.628922e+04,2.041331e+03,6.720000e+03,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,4912004.0,2.062367e+01,8.671533e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,4912004.0,3.983266e+00,1.980892e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
sample_point_sec,4912004.0,1.779131e+09,5.239794e+06,1.767222e+09,1.776032e+09,1.779150e+09,1.783335e+09,1.788905e+09
heart_rate,4912004.0,7.405498e+01,1.620638e+01,3.000000e+01,6.300000e+01,7.100000e+01,8.200000e+01,2.020000e+02

NUMERICAL SUMMARY: heart_rate_values_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,961.0,4.198837e+03,2.174552e+02,3.724000e+03,4.274000e+03,4.286000e+03,4.306000e+03,4.408000e+03
sdv_group_id,961.0,7.553381e+03,5.170103e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,961.0,1.779170e+09,5.225911e+06,1.767222e+09,1.776031e+09,1.779228e+09,1.783375e+09,1.788818e+09
end_measure_period_sec,961.0,1.779256e+09,5.225705e+06,1.767308e+09,1.776118e+09,1.779314e+09,1.783462e+09,1.788905e+09
duration_measure_period_sec,961.0,8.606660e+04,4.347218e+03,6.720000e+03,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,961.0,2.075754e+01,8.648128e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,961.0,4.011446e+00,1.989785e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
min_heart_rate_min,960.0,5.235521e+01,7.871483e+00,3.000000e+01,4.700000e+01,5.200000e+01,5.800000e+01,9.600000e+01
max_heart_rate_min,960.0,1.339875e+02,2.185777e+01,6.700000e+01,1.180000e+02,1.290000e+02,1.460000e+02,2.020000e+02
avg_heart_rate_min,960.0,7.462396e+01,7.436295e+00,5.700000e+01,7.000000e+01,7.400000e+01,8.000000e+01,1.100000e+02
rest_heart_rate_min,961.0,5.702289e+01,6.199756e+00,3.700000e+01,5.300000e+01,5.600000e+01,6.100000e+01,9.600000e+01

NUMERICAL SUMMARY: kilocalories_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,987.0,4.200755e+03,2.156566e+02,3.724000e+03,4.274000e+03,4.286000e+03,4.306000e+03,4.408000e+03
sdv_group_id,987.0,7.553390e+03,5.202031e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,987.0,1.779292e+09,5.253043e+06,1.767222e+09,1.776118e+09,1.779401e+09,1.783462e+09,1.788818e+09
end_measure_period_sec,987.0,1.779378e+09,5.252706e+06,1.767308e+09,1.776204e+09,1.779487e+09,1.783548e+09,1.788905e+09
duration_measure_period_sec,987.0,8.577684e+04,6.286301e+03,3.000000e+02,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,987.0,2.095846e+01,8.694225e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,987.0,4.020263e+00,1.990748e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
active_kilocalories,987.0,3.995633e+02,3.189889e+02,0.000000e+00,1.690000e+02,3.160000e+02,5.310000e+02,2.381000e+03
bmr_kilocalories,987.0,1.867301e+03,2.995042e+02,4.000000e+00,1.653000e+03,1.795000e+03,2.059000e+03,2.414000e+03

NUMERICAL SUMMARY: overall_sleep_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,299.0,3.975301e+03,2.706981e+02,3.724000e+03,3.760000e+03,3.760000e+03,4.286000e+03,4.408000e+03
sdv_group_id,299.0,7.553341e+03,5.471219e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,299.0,1.779837e+09,3.190983e+06,1.774566e+09,1.777068e+09,1.779228e+09,1.782684e+09,1.786226e+09
end_measure_period_sec,299.0,1.779924e+09,3.191018e+06,1.774652e+09,1.777154e+09,1.779314e+09,1.782770e+09,1.786313e+09
duration_measure_period_sec,299.0,8.612609e+04,2.828831e+03,4.770000e+04,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,299.0,2.185953e+01,5.281378e+00,1.300000e+01,1.700000e+01,2.100000e+01,2.700000e+01,3.200000e+01
week_day,299.0,4.016722e+00,1.995731e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
sleep_value,299.0,7.217057e+01,1.485549e+01,2.600000e+01,6.550000e+01,7.600000e+01,8.300000e+01,9.800000e+01

NUMERICAL SUMMARY: sleep_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,299.0,3.975301e+03,2.706981e+02,3.724000e+03,3.760000e+03,3.760000e+03,4.286000e+03,4.408000e+03
sdv_group_id,299.0,7.553341e+03,5.471219e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,299.0,1.779837e+09,3.190983e+06,1.774566e+09,1.777068e+09,1.779228e+09,1.782684e+09,1.786226e+09
end_measure_period_sec,299.0,1.779924e+09,3.191018e+06,1.774652e+09,1.777154e+09,1.779314e+09,1.782770e+09,1.786313e+09
duration_measure_period_sec,299.0,8.612609e+04,2.828831e+03,4.770000e+04,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,299.0,2.185953e+01,5.281378e+00,1.300000e+01,1.700000e+01,2.100000e+01,2.700000e+01,3.200000e+01
week_day,299.0,4.016722e+00,1.995731e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00

NUMERICAL SUMMARY: sleep_level_events_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,18402.0,4.202119e+03,2.104902e+02,3.724000e+03,4.274000e+03,4.274000e+03,4.306000e+03,4.408000e+03
sdv_group_id,18402.0,7.553485e+03,5.205493e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,18402.0,1.779315e+09,5.327286e+06,1.767222e+09,1.776118e+09,1.779314e+09,1.783721e+09,1.788818e+09
end_measure_period_sec,18402.0,1.779401e+09,5.327164e+06,1.767308e+09,1.776204e+09,1.779401e+09,1.783807e+09,1.788905e+09
duration_measure_period_sec,18402.0,8.621231e+04,2.704709e+03,2.382000e+04,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,18402.0,2.099103e+01,8.816437e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,18402.0,4.056461e+00,2.002503e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
start_sec,18402.0,1.779328e+09,5.327279e+06,1.767232e+09,1.776137e+09,1.779323e+09,1.783746e+09,1.788844e+09
end_sec,18402.0,1.779329e+09,5.327255e+06,1.767233e+09,1.776138e+09,1.779325e+09,1.783747e+09,1.788845e+09

NUMERICAL SUMMARY: steps_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,987.0,4.200755e+03,2.156566e+02,3.724000e+03,4.274000e+03,4.286000e+03,4.306000e+03,4.408000e+03
sdv_group_id,987.0,7.553390e+03,5.202031e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,987.0,1.779292e+09,5.253043e+06,1.767222e+09,1.776118e+09,1.779401e+09,1.783462e+09,1.788818e+09
end_measure_period_sec,987.0,1.779378e+09,5.252706e+06,1.767308e+09,1.776204e+09,1.779487e+09,1.783548e+09,1.788905e+09
duration_measure_period_sec,987.0,8.577684e+04,6.286301e+03,3.000000e+02,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,987.0,2.095846e+01,8.694225e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,987.0,4.020263e+00,1.990748e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
steps,987.0,6.802246e+03,5.643962e+03,0.000000e+00,3.151000e+03,5.302000e+03,8.851500e+03,4.702500e+04
steps_goal,987.0,8.027082e+03,3.617580e+03,2.780000e+03,5.985000e+03,8.000000e+03,1.000000e+04,3.000000e+04

NUMERICAL SUMMARY: stress_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,987.0,4.200755e+03,2.156566e+02,3.724000e+03,4.274000e+03,4.286000e+03,4.306000e+03,4.408000e+03
sdv_group_id,987.0,7.553390e+03,5.202031e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,987.0,1.779292e+09,5.253043e+06,1.767222e+09,1.776118e+09,1.779401e+09,1.783462e+09,1.788818e+09
end_measure_period_sec,987.0,1.779378e+09,5.252706e+06,1.767308e+09,1.776204e+09,1.779487e+09,1.783548e+09,1.788905e+09
duration_measure_period_sec,987.0,8.577684e+04,6.286301e+03,3.000000e+02,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,987.0,2.095846e+01,8.694225e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,987.0,4.020263e+00,1.990748e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
average_stress_level,987.0,3.243161e+01,1.227302e+01,-1.000000e+00,2.500000e+01,3.200000e+01,3.800000e+01,8.600000e+01
max_stress_level,960.0,9.436667e+01,6.449688e+00,3.200000e+01,9.300000e+01,9.600000e+01,9.900000e+01,1.000000e+02
stress_duration_sec,960.0,2.912775e+04,1.269687e+04,6.000000e+01,1.869000e+04,2.976000e+04,3.954000e+04,6.840000e+04
rest_stress_duration_sec,948.0,2.970063e+04,1.341997e+04,6.000000e+01,2.082000e+04,3.135000e+04,3.847500e+04,6.750000e+04
low_stress_duration_sec,958.0,1.621641e+04,8.366316e+03,6.000000e+01,1.003500e+04,1.536000e+04,2.190000e+04,4.446000e+04
medium_stress_duration_sec,956.0,9.028556e+03,5.655501e+03,6.000000e+01,4.605000e+03,8.280000e+03,1.248000e+04,3.510000e+04
high_stress_duration_sec,945.0,4.016952e+03,4.533460e+03,6.000000e+01,9.000000e+02,2.520000e+03,5.400000e+03,3.492000e+04
activity_stress_duration_sec,965.0,1.336750e+04,9.987531e+03,1.200000e+02,7.080000e+03,9.600000e+03,1.530000e+04,6.450000e+04

NUMERICAL SUMMARY: stress_level_sample_data

,count,mean,std,min,25%,50%,75%,max
sdv_user_id,460975.0,4.199134e+03,2.170695e+02,3.724000e+03,4.274000e+03,4.286000e+03,4.306000e+03,4.408000e+03
sdv_group_id,460975.0,7.553380e+03,5.174617e-01,7.552000e+03,7.553000e+03,7.553000e+03,7.554000e+03,7.554000e+03
start_measure_period_sec,460975.0,1.779330e+09,5.240222e+06,1.767222e+09,1.776118e+09,1.779401e+09,1.783548e+09,1.788818e+09
end_measure_period_sec,460975.0,1.779416e+09,5.240121e+06,1.767308e+09,1.776204e+09,1.779487e+09,1.783634e+09,1.788905e+09
duration_measure_period_sec,460975.0,8.622615e+04,2.830754e+03,3.000000e+02,8.640000e+04,8.640000e+04,8.640000e+04,9.000000e+04
week_nr,460975.0,2.102193e+01,8.675071e+00,1.000000e+00,1.600000e+01,2.100000e+01,2.800000e+01,3.700000e+01
week_day,460975.0,4.013734e+00,1.988962e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
sample_point_sec,460975.0,1.779373e+09,5.240262e+06,1.767222e+09,1.776169e+09,1.779430e+09,1.783583e+09,1.788905e+09
stress_level,460975.0,2.160563e+01,2.401784e+01,-2.000000e+00,-1.000000e+00,1.700000e+01,3.400000e+01,1.000000e+02